// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgIhU11Mpi0ZWNaT8q_q89i5-eDan-l44',
    appId: '1:618066976016:web:8eeb34d873f704ac3c5995',
    messagingSenderId: '618066976016',
    projectId: 'abindenurlaub-374f5',
    authDomain: 'abindenurlaub-374f5.firebaseapp.com',
    storageBucket: 'abindenurlaub-374f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAychfIFGjZpJZDeIa5TazeMm7Kd7OLRuQ',
    appId: '1:618066976016:android:b08e59ef089a8d383c5995',
    messagingSenderId: '618066976016',
    projectId: 'abindenurlaub-374f5',
    storageBucket: 'abindenurlaub-374f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8fHUxpZTpQRPzPKNgIfuc7tz5j9yEIcw',
    appId: '1:618066976016:ios:63a74a81d9c7609d3c5995',
    messagingSenderId: '618066976016',
    projectId: 'abindenurlaub-374f5',
    storageBucket: 'abindenurlaub-374f5.appspot.com',
    iosClientId: '618066976016-7r1pkush4vnjffc4djfv2rvfkfnop7ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.abInDenUrlaub',
  );
}
